import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';

import ToastProvider from '@/providers/toast-provider';


const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	

	return (
		<html lang='en'>
			<body className={nunito.className}>
				<ToastProvider />
				{children}
			</body>
		</html>
	);
}
